### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by billyvg** [getsentry/symbol-collector#90]
Travis sprung some surprise billing changes on us awhile, so we are now prioritizing removing usage of TravisCI completely. This issue will be used by @getsentry/productivity to track overall progress across the organization, but please let us know here if there's anything we should be aware of.

**Comment by bruno-garcia** [comment]
@billyvg this repo is very low in terms of changes. If it's critical I can just get rid of Travis right now and leave it without CI (and the burden to get GH actions will come next time we need to work on it). 

Otherwise I'll keep travis until .. one day, when we need to change the code and have time to change CI.

**Comment by billyvg** [comment]
@bruno-garcia For all of these issues I'm opening it's tracking for @getsentry/productivity team and (unless you have bandwidth), we will be doing the migration.

**Comment by bruno-garcia** [comment]
I'm ready to hear your rants. It was a pain to set this up :D

**Comment by bruno-garcia** [comment]
Resolved through #94
